"""initial schema

Revision ID: ab21f4687390
Revises: 
Create Date: 2026-09-03 16:01:50.419995

"""
from collections.abc import Sequence

# Autogenerate emits `pgvector.sqlalchemy.vector.VECTOR(...)` for vector columns
# but does not add the import itself. Imported unconditionally so every
# migration is runnable as generated.
import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab21f4687390'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_lookup', 'audit_log', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_run_id'), 'audit_log', ['run_id'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index('ix_audit_log_time', 'audit_log', ['occurred_at'], unique=False)
    op.create_table('tenants',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('active_policy_version', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parser_name', sa.String(length=64), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('tenant_id', 'content_hash', name='uq_document_content_hash')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('grn_number', sa.String(length=64), nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('received_by', sa.String(length=255), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'grn_number', name='uq_grn_number')
    )
    op.create_index(op.f('ix_goods_receipts_grn_number'), 'goods_receipts', ['grn_number'], unique=False)
    op.create_index(op.f('ix_goods_receipts_po_number'), 'goods_receipts', ['po_number'], unique=False)
    op.create_index(op.f('ix_goods_receipts_tenant_id'), 'goods_receipts', ['tenant_id'], unique=False)
    op.create_table('policy_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('citation_ref', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type IN ('accounting_policy','vendor_contract','coding_precedent')", name='ck_policy_chunks_doc_type'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_chunks_embedding_hnsw', 'policy_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_index('ix_policy_chunks_scope', 'policy_chunks', ['tenant_id', 'doc_type', 'version', 'effective_from', 'effective_to'], unique=False)
    op.create_index(op.f('ix_policy_chunks_tenant_id'), 'policy_chunks', ['tenant_id'], unique=False)
    op.create_index('ix_policy_chunks_tsv', 'policy_chunks', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_table('vendors',
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('erp_vendor_id', sa.String(length=64), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tax_id', sa.String(length=64), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('default_payment_terms', sa.String(length=32), nullable=True),
    sa.Column('bank_fingerprint', sa.String(length=512), nullable=True),
    sa.Column('bank_fingerprint_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vendor_id'),
    sa.UniqueConstraint('tenant_id', 'erp_vendor_id', name='uq_vendor_tenant_erp')
    )
    op.create_index('ix_vendors_legal_name_trgm', 'vendors', ['legal_name'], unique=False, postgresql_using='gin', postgresql_ops={'legal_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_vendors_tenant_id'), 'vendors', ['tenant_id'], unique=False)
    op.create_table('field_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('label_raw', sa.String(length=255), nullable=False),
    sa.Column('label_norm', sa.String(length=255), nullable=False),
    sa.Column('canonical_field', sa.String(length=64), nullable=False),
    sa.Column('confirmed_by', sa.String(length=255), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_applied', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'vendor_id', 'label_norm', name='uq_field_alias')
    )
    op.create_index(op.f('ix_field_aliases_tenant_id'), 'field_aliases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_field_aliases_vendor_id'), 'field_aliases', ['vendor_id'], unique=False)
    op.create_table('goods_receipt_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grn_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('quantity_received', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['grn_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_lines_grn_id'), 'goods_receipt_lines', ['grn_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('invoice_number', sa.String(length=128), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('vendor_name_raw', sa.String(length=255), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_terms', sa.String(length=64), nullable=True),
    sa.Column('po_reference', sa.String(length=64), nullable=True),
    sa.Column('remit_to_fingerprint', sa.String(length=512), nullable=True),
    sa.Column('header_confidence', sa.Float(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index('ix_invoices_amount_lookup', 'invoices', ['tenant_id', 'total_amount', 'invoice_date'], unique=False)
    op.create_index(op.f('ix_invoices_document_id'), 'invoices', ['document_id'], unique=False)
    op.create_index('ix_invoices_dup_lookup', 'invoices', ['tenant_id', 'vendor_id', 'invoice_number'], unique=False)
    op.create_index('ix_invoices_number_trgm', 'invoices', ['invoice_number'], unique=False, postgresql_using='gin', postgresql_ops={'invoice_number': 'gin_trgm_ops'})
    op.create_index(op.f('ix_invoices_po_reference'), 'invoices', ['po_reference'], unique=False)
    op.create_index(op.f('ix_invoices_tenant_id'), 'invoices', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_invoices_vendor_id'), 'invoices', ['vendor_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('po_number', sa.String(length=64), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('gl_account', sa.String(length=32), nullable=True),
    sa.Column('cost_center', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('project', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'po_number', name='uq_po_number')
    )
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=False)
    op.create_index(op.f('ix_purchase_orders_tenant_id'), 'purchase_orders', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_vendor_id'), 'purchase_orders', ['vendor_id'], unique=False)
    op.create_table('vendor_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('alias_raw', sa.String(length=255), nullable=False),
    sa.Column('alias_norm', sa.String(length=255), nullable=False),
    sa.Column('confirmed_by', sa.String(length=255), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'alias_norm', name='uq_vendor_alias_norm')
    )
    op.create_index(op.f('ix_vendor_aliases_tenant_id'), 'vendor_aliases', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_vendor_aliases_vendor_id'), 'vendor_aliases', ['vendor_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=32), nullable=True),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('po_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=32), nullable=True),
    sa.Column('gl_account', sa.String(length=32), nullable=True),
    sa.Column('cost_center', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_po_id'), 'purchase_order_lines', ['po_id'], unique=False)
    op.create_table('runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('model_calls', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('context_utilisation', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_runs_invoice_id'), 'runs', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_tenant_id'), 'runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_runs_trace_id'), 'runs', ['trace_id'], unique=False)
    op.create_table('check_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=8), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('threshold', sa.String(length=128), nullable=True),
    sa.Column('actual', sa.String(length=128), nullable=True),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('forces_review', sa.Boolean(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verdict IN ('pass','flag','fail','skip')", name='ck_check_results_verdict'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_check_results_analysis', 'check_results', ['tenant_id', 'name', 'verdict'], unique=False)
    op.create_index('ix_check_results_lookup', 'check_results', ['run_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_check_results_run_id'), 'check_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_check_results_tenant_id'), 'check_results', ['tenant_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('route', sa.String(length=32), nullable=False),
    sa.Column('decided_by', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gl_account', sa.String(length=32), nullable=True),
    sa.Column('cost_center', sa.String(length=64), nullable=True),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('project', sa.String(length=64), nullable=True),
    sa.Column('gl_confidence', sa.Float(), nullable=True),
    sa.Column('gl_inherited_from_po', sa.Boolean(), nullable=False),
    sa.Column('required_approver_tier', sa.String(length=64), nullable=True),
    sa.Column('approver_identity', sa.String(length=255), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_due_date', sa.Date(), nullable=True),
    sa.Column('discount_deadline', sa.Date(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('discount_annualised_pct', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("NOT (decided_by = 'agent' AND approver_identity IS NOT NULL)", name='ck_decisions_sod_agent_not_approver'),
    sa.CheckConstraint("NOT (route = 'auto_approve' AND decided_by = 'human')", name='ck_decisions_auto_approve_not_human'),
    sa.CheckConstraint("decided_by IN ('agent','human','policy_engine')", name='ck_decisions_actor'),
    sa.CheckConstraint("route IN ('auto_approve','hold','route_for_approval','reject')", name='ck_decisions_route'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index(op.f('ix_decisions_invoice_id'), 'decisions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_decisions_route'), 'decisions', ['route'], unique=False)
    op.create_index(op.f('ix_decisions_tenant_id'), 'decisions', ['tenant_id'], unique=False)
    op.create_table('erp_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('erp_object_id', sa.String(length=64), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_erp_action_idem')
    )
    op.create_index(op.f('ix_erp_actions_invoice_id'), 'erp_actions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_erp_actions_run_id'), 'erp_actions', ['run_id'], unique=False)
    op.create_index(op.f('ix_erp_actions_status'), 'erp_actions', ['status'], unique=False)
    op.create_index(op.f('ix_erp_actions_tenant_id'), 'erp_actions', ['tenant_id'], unique=False)
    op.create_table('hitl_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('required_tier', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('thread_id', sa.String(length=128), nullable=True),
    sa.Column('interrupt_id', sa.String(length=128), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('decision_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','edited','rejected','expired')", name='ck_hitl_status'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hitl_reviews_invoice_id'), 'hitl_reviews', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_hitl_reviews_run_id'), 'hitl_reviews', ['run_id'], unique=False)
    op.create_index(op.f('ix_hitl_reviews_status'), 'hitl_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_hitl_reviews_tenant_id'), 'hitl_reviews', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_hitl_reviews_thread_id'), 'hitl_reviews', ['thread_id'], unique=False)
    op.create_table('run_errors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('error_class', sa.String(length=32), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_errors_error_class'), 'run_errors', ['error_class'], unique=False)
    op.create_index(op.f('ix_run_errors_run_id'), 'run_errors', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_errors_run_id'), table_name='run_errors')
    op.drop_index(op.f('ix_run_errors_error_class'), table_name='run_errors')
    op.drop_table('run_errors')
    op.drop_index(op.f('ix_hitl_reviews_thread_id'), table_name='hitl_reviews')
    op.drop_index(op.f('ix_hitl_reviews_tenant_id'), table_name='hitl_reviews')
    op.drop_index(op.f('ix_hitl_reviews_status'), table_name='hitl_reviews')
    op.drop_index(op.f('ix_hitl_reviews_run_id'), table_name='hitl_reviews')
    op.drop_index(op.f('ix_hitl_reviews_invoice_id'), table_name='hitl_reviews')
    op.drop_table('hitl_reviews')
    op.drop_index(op.f('ix_erp_actions_tenant_id'), table_name='erp_actions')
    op.drop_index(op.f('ix_erp_actions_status'), table_name='erp_actions')
    op.drop_index(op.f('ix_erp_actions_run_id'), table_name='erp_actions')
    op.drop_index(op.f('ix_erp_actions_invoice_id'), table_name='erp_actions')
    op.drop_table('erp_actions')
    op.drop_index(op.f('ix_decisions_tenant_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_route'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_invoice_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_check_results_tenant_id'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_run_id'), table_name='check_results')
    op.drop_index('ix_check_results_lookup', table_name='check_results')
    op.drop_index('ix_check_results_analysis', table_name='check_results')
    op.drop_table('check_results')
    op.drop_index(op.f('ix_runs_trace_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_tenant_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_invoice_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_purchase_order_lines_po_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_vendor_aliases_vendor_id'), table_name='vendor_aliases')
    op.drop_index(op.f('ix_vendor_aliases_tenant_id'), table_name='vendor_aliases')
    op.drop_table('vendor_aliases')
    op.drop_index(op.f('ix_purchase_orders_vendor_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_tenant_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_invoices_vendor_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_tenant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_po_reference'), table_name='invoices')
    op.drop_index('ix_invoices_number_trgm', table_name='invoices', postgresql_using='gin', postgresql_ops={'invoice_number': 'gin_trgm_ops'})
    op.drop_index('ix_invoices_dup_lookup', table_name='invoices')
    op.drop_index(op.f('ix_invoices_document_id'), table_name='invoices')
    op.drop_index('ix_invoices_amount_lookup', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_goods_receipt_lines_grn_id'), table_name='goods_receipt_lines')
    op.drop_table('goods_receipt_lines')
    op.drop_index(op.f('ix_field_aliases_vendor_id'), table_name='field_aliases')
    op.drop_index(op.f('ix_field_aliases_tenant_id'), table_name='field_aliases')
    op.drop_table('field_aliases')
    op.drop_index(op.f('ix_vendors_tenant_id'), table_name='vendors')
    op.drop_index('ix_vendors_legal_name_trgm', table_name='vendors', postgresql_using='gin', postgresql_ops={'legal_name': 'gin_trgm_ops'})
    op.drop_table('vendors')
    op.drop_index('ix_policy_chunks_tsv', table_name='policy_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_policy_chunks_tenant_id'), table_name='policy_chunks')
    op.drop_index('ix_policy_chunks_scope', table_name='policy_chunks')
    op.drop_index('ix_policy_chunks_embedding_hnsw', table_name='policy_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_table('policy_chunks')
    op.drop_index(op.f('ix_goods_receipts_tenant_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_po_number'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_grn_number'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('tenants')
    op.drop_index('ix_audit_log_time', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_run_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_lookup', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
